-- Crear la tabla principal para Cercos Eléctricos
CREATE TABLE IF NOT EXISTS public.servicios_cercos_electricos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    orden_numero TEXT,
    fecha DATE,
    
    -- Información del Cliente y General
    cliente_nombre TEXT,
    cliente_telefono TEXT,
    tecnico_nombre TEXT,
    ubicacion_instalacion TEXT,
    estatus TEXT DEFAULT 'recibido',
    
    -- Detalles dinámicos o descriptivos generales
    problema_reportado TEXT,
    diagnostico_tecnico TEXT,
    trabajo_realizado TEXT,
    
    -- Mapeo de Categoría
    sistema_tipo TEXT DEFAULT 'Cercos Electricos',
    sistema_modelo TEXT,
    
    -- Información Financiera
    mano_obra NUMERIC DEFAULT 0,
    repuestos_costo NUMERIC DEFAULT 0,
    anticipo NUMERIC DEFAULT 0,
    incluir_iva BOOLEAN DEFAULT false,
    iva NUMERIC DEFAULT 0,
    subtotal NUMERIC DEFAULT 0,
    total NUMERIC DEFAULT 0,
    pagado BOOLEAN DEFAULT false,
    entregado BOOLEAN DEFAULT false,
    
    -- Payload JSONB para todo el contenido dinámico del Cerco
    inventario_materiales JSONB DEFAULT '[]'::jsonb,
    contenido_dinamico JSONB DEFAULT '{}'::jsonb
);

-- Políticas RLS (Row Level Security) para igualar el nivel de los demás servicios
ALTER TABLE public.servicios_cercos_electricos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own cercos electricos"
    ON public.servicios_cercos_electricos FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own cercos electricos"
    ON public.servicios_cercos_electricos FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own cercos electricos"
    ON public.servicios_cercos_electricos FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own cercos electricos"
    ON public.servicios_cercos_electricos FOR DELETE
    USING (auth.uid() = user_id);
